name: Dev Build

on:
  push:
    branches:
      - publish-dev/**

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    
    - name: Checkout
      uses: actions/checkout@v1

    - name: Check License Lines
      uses: kt3k/license_checker@v1.0.6

    - name: Setup .NET 7.0
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: 7.0.x

    - name: Build
      run: dotnet build Mindbox.I18n.sln --configuration Release
      
    - name: Test
      run: dotnet test Mindbox.I18n.sln --no-build --configuration Release

    - name: Pack
      run: dotnet pack Mindbox.I18n.sln -c Release -p:BuildNumber=${{ github.run_number }} -p:VersionTag="-dev"

    - name: Publish
      run: dotnet nuget push **/*.nupkg -k ${{secrets.MINDBOX_NUGET_AUTH_TOKEN}} -s https://www.nuget.org/api/v2/package